### ISSUE TITLE
Support for relationships?

### ISSUE THREAD

**Issue by MrToxy** [overtrue/laravel-versionable#10]
Are relationships supported?

**Comment by overtrue** [comment]
please show me an example.

**Comment by MrToxy** [comment]
So basically what I'm trying to say is that it would be an amazing feature to be able to version a models relationships.
Picture this.

```php
$order = Order::find(10);
$provider = Provider::find(10);

// It would be amazing to allow the relationship changes to also be tracked
$order->provider()->associate($provider);
```

A more specific use case for this would be the following:

Imagine an order that has activity items as a relationship, the activity item also has tickets and addons.
A new order is placed with 2 activity items, the client is charged and later on needs to edit the order, he edits the order but doesn't pay right away, if by the 2nd after editing the order the client doesn't pay I would like to return the order and the activity items back to they're original state.

**Comment by overtrue** [comment]
I think you can override `getVersionableAttributes` to define which methods will be versionable.

https://github.com/overtrue/laravel-versionable/blob/master/src/Versionable.php#L112 

<blockquote><img src="https://avatars1.githubusercontent.com/u/1472352?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/overtrue/laravel-versionable">overtrue/laravel-versionable</a></strong></div><div>⏱️Make Laravel model versionable. Contribute to overtrue/laravel-versionable development by creating an account on GitHub.</div></blockquote>

**Comment by MTEXX** [comment]
@MrToxy did you find a solution for this?
