### ISSUE TITLE
lastVersion and latestVersion should return the latest and not the first

### ISSUE THREAD

**Issue by 4unkur** [overtrue/laravel-versionable#26]
The docs are misleading. When I call:   
```php
$model->lastVersion;
```

I am expecting to get the latest version but I get the first. I see in the sources that it returns `latest()` relationship, so to get the latest version I have to use:
```php
$model->lastVersion()->first();
```
In this case I get what I expect.
Suggestion: Edit the docs or update the code

**Comment by overtrue** [comment]
plz show me your code, because the are the same result in Laravel:

```php
$model->lastVersion;      
$model->lastVersion()->first();
```

> https://laravel.com/docs/8.x/eloquent-relationships#one-to-one
> we may retrieve the related record using Eloquent's dynamic properties. Dynamic properties allow you to access relationship methods as if they were properties defined on the model

**Comment by overtrue** [comment]
Plz, paste your code, because they are same result in laravel:

```php
$model->lastVersion;
$model->lastVersion()->first();
```

**Comment by 4unkur** [comment]
@overtrue I have rechecked and found that issue was due to the missing `$model->refresh()` call.  

Here's the failing test:
```php
    public function it_returns_latest_version()
    {
        $post = Post::create(['title' => 'version1', 'content' => 'version1 content']);
        $firstVersion = $post->lastVersion;

        $post->update(['title' => 'version2']);
        $post->update(['title' => 'version3']);
        $post->update(['title' => 'version4']);

        $this->assertEquals(
            $post->latestVersion()->first()->id,
            $post->lastVersion->id
        );

        $this->assertNotEquals(
            $firstVersion->id,
            $post->lastVersion->id,
        );
    }
```

The second assertion is failing. In order to fix: `$post->refresh()` should be executed.
My bad.

Thanks.

**Comment by overtrue** [comment]
Yes, because relations were cached.
