### ISSUE TITLE
Incorrect usage of revertWithoutSaving in the docs

### ISSUE THREAD

**Issue by 4unkur** [overtrue/laravel-versionable#27]
https://github.com/overtrue/laravel-versionable#reversion-without-saving

here it says that the method can be used on the model but in fact the method belongs to the Version model, so the correct way of usage would be:
```php
$version = $post->versions()->first(); // just as an example
$version->revertWithoutSaving();
```

**Comment by overtrue** [comment]
Thank you for your feedback.

**Comment by 4unkur** [comment]
Yes, would be nice to have docs updated.
