### ISSUE TITLE
Is there any way to save the first record?

### ISSUE THREAD

**Issue by Viturbiko** [overtrue/laravel-versionable#29]
Hello, when I create a record, for example a user with name "John", and it changes it to "Charles", is there any way to get the original first name, "John"? Because it seems that I can just get the changes, in this case, "Charles", but then I lose a lot of information for that first change.

Thank you so much.

**Comment by overtrue** [comment]
```php

$version = $post->versions()->first(); 

$post = $version->revertWithoutSaving();

```

**Comment by Viturbiko** [comment]
But then I can get the first changes of the versions table, not the first created model. Doing that, in the example above, I will get "name" => "Charles", because I get the first change made, not the original name on the User::create(), that was "John".
