### ISSUE TITLE
Change data type for foreign keys

### ISSUE THREAD

**Issue by dmytrozelonkin** [overtrue/laravel-versionable#3]
It would be nice to change data type for user_id and versionable_id columns from unsignedBigInteger to uuid.

**Comment by overtrue** [comment]
You can publish the migration file and update it.

Dmitry Zelonkin <notifications@github.com>于2019年6月5日 周三下午6:38写道：

**Comment by dmytrozelonkin** [comment]
@overtrue your command for publishing migrations is wrong. should be --tag=migrations - s letter in the end.

**Comment by overtrue** [comment]
I am sorry, I will fix it.

Dmitry Zelonkin <notifications@github.com>于2019年6月6日 周四上午4:37写道：
