### ISSUE TITLE
Error when updating or saving from job

### ISSUE THREAD

**Issue by Viturbiko** [overtrue/laravel-versionable#30]
Hello, I have an issue when using this package through a job. I think the problem is in this line:

`$version->{\config('versionable.user_foreign_key')} = \auth()->id();` line 64 in Version.php.

When running a job, auth()->id() returns null, so it throws an error and it doesnt save changes. Is there any way to fix this?

Thanks a lot.

**Comment by overtrue** [comment]
@Viturbiko I have added a method `getVersionUserId()` to Versionable trait https://github.com/overtrue/laravel-versionable/commit/e0afe3f04046fedec2c6e0dc611c64965d509adf . it will try to get the attribute such as `user_id` from model and you can also override this method to custom return user id.
