### ISSUE TITLE
Versions diff

### ISSUE THREAD

**Issue by invaders-xx** [overtrue/laravel-versionable#34]
Is there a way to display diff between 2 versions ?

**Comment by overtrue** [comment]
Hi, @invaders-xx I've released [4.0.0](https://github.com/overtrue/laravel-versionable/releases/tag/4.0.0) with a [new diff implementation](https://github.com/overtrue/laravel-versionable#show-diff-between-two-versions).

**Comment by invaders-xx** [comment]
Great ! many thanks @overtrue !
