### ISSUE TITLE
Multiple Database Support

### ISSUE THREAD

**Issue by ryangurn** [overtrue/laravel-versionable#36]
I have been working on a project that utilizes multiple database connections and I want versioning within all of the databases.

I published the migrations and updated them to create the version tables within each of the databases. This worked perfectly, however, when saving or deleting a records from a versionable table it only puts records into the **default** database which is not the desired outcome. 

It would be useful if the versionable trait would use a pass through of the connection from the model to be used on the version model. 

This would require that the versions table exist in any database with a versionable table contained within it, but my opinion is that the versions table should exist within **all** databases regardless of use (within that database).

I am currently looking through this packages code to implement a possible solution to make this work, but I have not come up with anything at the moment.

**Comment by ryangurn** [comment]
If you have an alternate solution that would work, I am all ears but I think that it should just use the database connection from  model with the versionable trait on it.

**Comment by ryangurn** [comment]
I have made an adjustment to the version model that will use the developers model connection for the version model. 

Please let me know if any adjustments need to be made to the attached PR.

**Comment by ryangurn** [comment]
@overtrue, thanks for merging that in.

I have some ideas that might be useful for supporting multiple databases, I will submit PR's when I figure out the best way to implement them.

**Comment by overtrue** [comment]
Thank you for your contribution.
