### ISSUE TITLE
Question: Syntax for blacklisting

### ISSUE THREAD

**Issue by ryangurn** [overtrue/laravel-versionable#38]
In the readme, it is mentioned that specific attributes can be blacklisted instead of whitelisting a variety of fields.

Can you please explain how this is done since it is not explicit in the readme about the process.

**Comment by ryangurn** [comment]
Is it the protected variable `$dontVersionable` within the model?

**Comment by overtrue** [comment]
@ryangurn Yes, I've updated the readme.

**Comment by ryangurn** [comment]
Thanks!
