### ISSUE TITLE
Versions are being created even if the versionable fields are not changed with snapshot strategy

### ISSUE THREAD

**Issue by 4unkur** [overtrue/laravel-versionable#41]
For the demo purpose I have created a repo with example. Just clone and install the dependencies. It's a fresh Laravel 9 app.
Versionable model:

https://github.com/4unkur/laravel-versionable-example/blob/master/app/Models/SurveyTemplate.php

has 2 versionable fields. The strategy is SNAPSHOT

Failing test:
https://github.com/4unkur/laravel-versionable-example/blob/master/tests/Feature/VersionTest.php
I'm expecting that no versions will be created if the versionable fields are not touched. I don't think Snapshot strategy is the problem as in my understanding it is related to the data stored in the versions: all versionable fields or just changed ones.

**Comment by overtrue** [comment]
@4unkur Sorry for missing this issue, I have fixed the bug and tested it with your code, please upgrade to 4.1.0 to fix the issue, thanks!

**Comment by 4unkur** [comment]
Hi, no problem. Thanks for the fix
