### ISSUE TITLE
versionable_id as uuid

### ISSUE THREAD

**Issue by alex-mcarrow** [overtrue/laravel-versionable#47]
versionable_id throw error because id is UUID:

SQLSTATE[01000]: Warning: 1265 Data truncated for column 'versionable_id' at row 1 (Connection: mysql, SQL: insert into `versions` (`versionable_id`, `versionable_type`, `user_id`, `contents`, `updated_at`, `created_at`) values (98f5f55d-00f6-4577-8e1f-782526c17c27, App\Models\Contact, 1, {"last_name":"\u0439\u0446\u0443\u043ag1","updated_at":"2023-04-19T11:53:18.000000Z"}, 2023-04-19 14:53:18, 2023-04-19 14:53:18))

**Comment by overtrue** [comment]
@alex-mcarrow If you want to support the uuid format, you need to change the versionable_id field to the corresponding format:

php artisan vendor:publish --provider="Overtrue\LaravelVersionable\ServiceProvider" --tag=migrations

Then change it to:

*database/migrations/2019_05_31_042934_create_versions_table.php*

```diff
-$table->morphs('versionable');
+$table->uuidMorphs('versionable');
```

Then run migrate command:

```bash
PHP artisan migrate
```

**Comment by tonypartridge** [comment]
Yep FYI I did this a few months ago and it's been fine. @overtrue it might be an idea to chuck it as a config option prior to migration?

**Comment by overtrue** [comment]
> 

Good idea, I will add this feature in a few days, or feel free to make a PR. Thanks.
