### ISSUE TITLE
decimal类型的字段，会因为结尾的0，误认为字段有新的version

### ISSUE THREAD

**Issue by ChenRuihua** [overtrue/laravel-versionable#5]
字段类型 decimal(10,4)。数据库里的值是4.1000。
此时如果再提交4.1到数据库，会产生新的version，值是4.1 
但其实在数据库里依旧会被存为4.1000

**Comment by overtrue** [comment]
感谢反馈，这里的变更主要取决于 Laravel Model 的 `isDirty`:

判断是否有变更：
https://github.com/overtrue/laravel-versionable/blob/master/src/Versionable.php#L93-L96

获取变更的内容:
https://github.com/overtrue/laravel-versionable/blob/master/src/Versionable.php#L101-L110

如果您有特殊的情况不想产生新的版本，你可以覆盖这俩方法的逻辑即可。

<blockquote><img src="https://avatars1.githubusercontent.com/u/1472352?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/overtrue/laravel-versionable">overtrue/laravel-versionable</a></strong></div><div>⏱️Make Laravel model versionable. Contribute to overtrue/laravel-versionable development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/1472352?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/overtrue/laravel-versionable">overtrue/laravel-versionable</a></strong></div><div>⏱️Make Laravel model versionable. Contribute to overtrue/laravel-versionable development by creating an account on GitHub.</div></blockquote>

**Comment by ChenRuihua** [comment]
谢谢解答
