### ISSUE TITLE
VersionStrategy::SNAPSHOT saves all attributes instead of all versionable attributes

### ISSUE THREAD

**Issue by mansoorkhan96** [overtrue/laravel-versionable#54]
The VersionStrategy::SNAPSHOT saves all the Model attributes instead of saving on the ones specified using: 

```php
protected $versionable = ['title', 'content'];
```

I think this is because of `$this->getAttributes()` in following code?

```php
// Versionable.php, line: 215

if ($this->getVersionStrategy() === VersionStrategy::SNAPSHOT && (! empty($changes) || ! empty($attributes))) {
    $changedKeys = array_keys($this->getAttributes());
}
```

It should be `$changedKeys = array_keys($this->getVersionable());` ?

Or we can even add a completely new strategy?

**Comment by overtrue** [comment]
I am working on this.

**Comment by mansoorkhan96** [comment]
Right now, changing the logic for `VersionStrategy::SNAPSHOT` might introduce a breaking change.

**Comment by mansoorkhan96** [comment]
> I am working on this.

Great.

Thanks!

**Comment by overtrue** [comment]
What do you think the following definitions:

- **DIFF**:  Changed attributes in the `$versionable`
- **SNAPSHOT**: All the attributes in the `$versionable`, not all of the model attributes.

**Comment by overtrue** [comment]
so maybe we should add a strategy named `FULL_SNAPSHOT ` ?  or any other name?

**Comment by mansoorkhan96** [comment]
> What do you think the following definitions:
> 
> * **DIFF**:  Changed attributes in the `$versionable`
> * **SNAPSHOT**: All the attributes in the `$versionable`, not all of the model attributes.

Thats the ideal definition.

But.. Would not it introduce a breaking change? Users might be using SNAPSHOT to save all the Model attributes and now when they upgrade they would only see the $versionable attributes.

**Comment by mansoorkhan96** [comment]
> so maybe we should add a strategy named `FULL_SNAPSHOT ` ? or any other name?

FULL_SNAPSHOT is nice

**Comment by overtrue** [comment]
> > What do you think the following definitions:
> > 
> > * **DIFF**:  Changed attributes in the `$versionable`
> > * **SNAPSHOT**: All the attributes in the `$versionable`, not all of the model attributes.
> 
> Thats the ideal definition.
> 
> But.. Would not it introduce a breaking change? Users might be using SNAPSHOT to save all the Model attributes and now when they upgrade they would only see the $versionable attributes.

Yes, we can create a major version.

**Comment by mansoorkhan96** [comment]
> > > What do you think the following definitions:
> > > 
> > > * **DIFF**:  Changed attributes in the `$versionable`
> > > * **SNAPSHOT**: All the attributes in the `$versionable`, not all of the model attributes.
> > 
> > 
> > Thats the ideal definition.
> > But.. Would not it introduce a breaking change? Users might be using SNAPSHOT to save all the Model attributes and now when they upgrade they would only see the $versionable attributes.
> 
> Yes, we can create a major version.

Great, we are good then.

* DIFF: Changed attributes in the $versionable
* SNAPSHOT: All the attributes in the $versionable, not all of the model attributes.
* FULL_SNAPSHOT or FULL or COMPLETE or ALL: All of the model attributes.

Now that you are releasing a major version. Maybe refactor VersionStrategy class to an enum?

**Comment by overtrue** [comment]
> > > > What do you think the following definitions:
> > > > 
> > > > * **DIFF**:  Changed attributes in the `$versionable`
> > > > * **SNAPSHOT**: All the attributes in the `$versionable`, not all of the model attributes.
> > > 
> > > 
> > > Thats the ideal definition.
> > > But.. Would not it introduce a breaking change? Users might be using SNAPSHOT to save all the Model attributes and now when they upgrade they would only see the $versionable attributes.
> > 
> > 
> > Yes, we can create a major version.
> 
> Great, we are good then.
> 
> * DIFF: Changed attributes in the $versionable
> * SNAPSHOT: All the attributes in the $versionable, not all of the model attributes.
> * FULL_SNAPSHOT or FULL or COMPLETE or ALL: All of the model attributes.
> 
> Now that you are releasing a major version. Maybe refactor VersionStrategy class to an enum?

Great idea!

**Comment by overtrue** [comment]
Here's a query, I don't know what you think, I think that the DIFF model probably shouldn't exist, for example:

```php 
// model Post protected $versionable = ['title', 'content', 'extends'];

$post = Post::create(['title' => 'version1', 'content' => 'version1 content']); $post->update(['title' => 'version2', 'extends' => ['foo' => 'bar' ]]); $post->versions.

$post->versions: 
//[id => 1, 'title' => 'version1', 'content' => 'version1 content']
//[id => 2, 'title' => 'version2', extends => ['foo' => 'bar'] ] ```

If we roll back to version 1, we will get unexpected results:

```php
$post->firstVersion->revert(); dd($post->extends); // ['foo' => 'bar'] 
```

Because the implementation logic is taking the version 1 `contents (title, content)` and overriding the current field `(title,content)`, the `extends` are not overridden, leading to the wrong result, and since `extends` is in the versionable, it looks like a bug.

**Comment by mansoorkhan96** [comment]
> Here's a query, I don't know what you think, I think that the DIFF model probably shouldn't exist, for example:
> 
> ```
> // model Post protected $versionable = ['title', 'content', 'extends'];
> 
> $post = Post::create(['title' => 'version1', 'content' => 'version1 content']); $post->update(['title' => 'version2', 'extends' => ['foo' => 'bar' ]]); $post->versions.
> 
> $post->versions: 
> //[id => 1, 'title' => 'version1', 'content' => 'version1 content']
> //[id => 2, 'title' => 'version2', extends => ['foo' => 'bar'] ] ```
> 
> If we roll back to version 1, we will get unexpected results:
> 
> ```php
> $post->firstVersion->revert(); dd($post->extends); // ['foo' => 'bar'] 
> ```
> 
> Because the implementation logic is taking the version 1 `contents (title, content)` and overriding the current field `(title,content)`, the `extends` are not overridden, leading to the wrong result, and since `extends` is in the versionable, it looks like a bug.

Let me try that.

**Comment by mansoorkhan96** [comment]
@overtrue I think you are right. Reverting with DIFF is complex, because you dont have the attributes and you dont know what was the state for the unchanged attributes in that version.

**Comment by overtrue** [comment]
yes, so i think we will remove this strategy. 🤣

**Comment by overtrue** [comment]
I am working on branch 5.x

**Comment by overtrue** [comment]
Let's do some work first and keep changing it later, feel free to discuss any comments, thanks!

**Comment by mansoorkhan96** [comment]
> Let's do some work first and keep changing it later, feel free to discuss any comments, thanks!

Great. Let me know if you want to assign anything to me.

**Comment by overtrue** [comment]
For now I'm hoping that when I'm done with the changes you can help verify that all of your needs are met and that your package is working properly, thanks!

**Comment by mansoorkhan96** [comment]
> For now I'm hoping that when I'm done with the changes you can help verify that all of your needs are met and that your package is working properly, thanks!

No problems, I will do that.

**Comment by overtrue** [comment]
Hi, I've found a problem, if you are in diff mode, the revert version should be stacked with all the versions from the initial version, while snapshot will just use that version.

**Comment by overtrue** [comment]
revert to version 3
DIFF:  `array_merge(version 1, version 2, version 3)`

so we must keep the first version with full mode:

```php
if ($post->isFirstVersion()) {
   $version->contents = $post->refresh()->getAttributes();
} else {
   $version->contents = by strategy.
}
```

**Comment by overtrue** [comment]
These three schemas have the following characteristics:

1. **DIFF** 
1.1. the initialized version is for all fields and is required to get the default values of the fields from the database; 
1.2. the version history keeps only every change; 
1.3. rollbacks are stacked chronologically from the initialization version to the target version; 
1.4. deleting a version **will affect** rollback behavior. 

2. **SNAPSHOT** 
2.1. the initialized version is for all fields and is required to get the default values of the fields from the database; 
2.2. the version history keeps only the fields that were changed in each $versionables; 
2.3. the initial version + the target version is sufficient for rollback; 
2.4. deleting the version will **not affect** the rollback behavior. 

3. **FULL/ALL** 
3.1. the initialized version is for all fields and is required to get the default values of the fields from the database; 
3.2. the version history keeps all fields; 
3.3. the target version can be used directly for rollback; 
3.4. deleting the version will **not affect** the rollback behavior.

**Comment by overtrue** [comment]
In this way, SNAPSHOT mode can actually be a new version of FULL mode, keeping the original DIFF and SNAPSHOT, and just changing the implementation to the FULL effect. The catch here is that the first version must be the full version.

**Comment by mansoorkhan96** [comment]
> These three schemas have the following characteristics:
> 
> 1. **DIFF**
>    1.1. the initialized version is for all fields and is required to get the default values of the fields from the database;
>    1.2. the version history keeps only every change;
>    1.3. rollbacks are stacked chronologically from the initialization version to the target version;
>    1.4. deleting a version **will affect **rollback behavior.
> 2. **SNAPSHOT**
>    2.1. the initialized version is for all fields and is required to get the default values of the fields from the database;
>    2.2. the version history keeps only the fields that were changed in each $versionables;
>    2.3. the initial version + the target version is sufficient for rollback;
>    2.4. deleting the version will **not affect** the rollback behavior.
> 3. **FULL/ALL**
>    3.1. the initialized version is for all fields and is required to get the default values of the fields from the database;
>    3.2. the version history keeps all fields;
>    3.3. the target version can be used directly for rollback;
>    3.4. deleting the version will **not affect** the rollback behavior.

I dont understand the problem you mentioned above.

But 2.2 could be following?
2.2. the version history keeps all the $versionables fields; if any of the  $versionables fields has changed.

yes.

**Comment by overtrue** [comment]
I mean, my original implementation of "revert" was wrong, my original implementation was:


```php
$post->revertTo($targetVersion);
```

1. Fetch $targetVersion `contents` 
2. Merge `$post->all()` and `$targetVersion->contents`

the step 2 is wrong, it is `latest attributes` + `$targetVersion->contents`.

it should be `first full attributes` + ($versions)... + `$targetVersion->contents`.

do you understand?

**Comment by mansoorkhan96** [comment]
> I mean, my original implementation of "revert" was wrong, my original implementation was:
> 
> ```
> $post->revertTo($targetVersion);
> ```
> 
> 1. Fetch $targetVersion `contents`
> 2. Merge `$post->all()` and `$targetVersion->contents`
> 
> the step 2 is wrong, it is `latest attributes` + `$targetVersion->contents`.
> 
> it should be `first full attributes` + ($versions)... + `$targetVersion->contents`.
> 
> do you understand?

> it should be first full attributes + ($versions)... + $targetVersion->contents.

Well this might be necessary for the DIFF mode, because we only have certain fields in some versions.

But for snapshot, we will have all the fields we care about and can revert easily to any target version we need.

For my usecase, i might eventually write my own revert, as i would allow the user to revert only selected fields.

**Comment by overtrue** [comment]
So, I think the new version will have two strategy like this:

1. DIFF
- init with all attributes(refreshed from database)
- save changed attributes(subset of $versionable)
- rollback: init version + all of versions to $targetVersion + attributes not in the $versionable of latest version.

example:

```php
$post = Post::create(['title' => 'Init title', 'type' => 'Blog', 'status' => 'published'])
$post->update(['title' => 'version 2 title']);
$post->update(['status' => 'draft']); // no version
$post->update(['type' => 'Vlog']);

// versions:
// ['id' => 1, 'title' => 'Init title', 'type' => 'Blog', 'status' => 'published']
// ['id' => 2, 'title' => 'version 2 title']
// ['id' => 3, 'type' => 'vlog']

$post->revert(2);
// [
//      'title' => 'version 2 title', 
//      'type' => 'Blog', 
//      'status' => 'draft' // latest value, because this field is not in $versionable
// ]

```

3. SNAPSHOT
- init with all attributes(refreshed from database)
- save all attributes
- rollback: $targetVersion

**Comment by mansoorkhan96** [comment]
> So, I think the new version will have two strategy like this:
> 
> 1. DIFF
> 
> * init with all attributes(refreshed from database)
> * save changed attributes(subset of $versionable)
> * rollback: init version + all of versions to $targetVersion + attributes not in the $versionable of latest version.
> 
> example:
> 
> ```
> $post = Post::create(['title' => 'Init title', 'type' => 'Blog', 'status' => 'published'])
> $post->update(['title' => 'version 2 title']);
> $post->update(['status' => 'draft']); // no version
> $post->update(['type' => 'Vlog']);
> 
> // versions:
> // ['id' => 1, 'title' => 'Init title', 'type' => 'Blog', 'status' => 'published']
> // ['id' => 2, 'title' => 'version 2 title']
> // ['id' => 3, 'type' => 'vlog']
> 
> $post->revert(2);
> // [
> //      'title' => 'version 2 title', 
> //      'type' => 'Blog', 
> //      'status' => 'draft' // latest value, because this field is not in $versionable
> // ]
> ```
> 
> 3. SNAPSHOT
> 
> * init with all attributes(refreshed from database)
> * save all attributes
> * rollback: $targetVersion

I trust your instincts. Do it if its the best way to get around it ❤️

> init with all attributes(refreshed from database)

But maybe lets make the saving all attributes functionality optional. Because then the diff could get messy.


<img width="891" alt="image" src="https://github.com/overtrue/laravel-versionable/assets/51432274/654f2d7c-daca-4c40-9644-8328ba49391e">

**Comment by overtrue** [comment]
@mansoorkhan96 Yes, the default strategy is DIFF, so do you think it's better to snapshot $versionable rather than snapshot all attributes?

**Comment by mansoorkhan96** [comment]
> @mansoorkhan96 Yes, the default strategy is DIFF, so do you think it's better to snapshot $versionable rather than snapshot all attributes?

I think its better to keep $versionable attributes only, when user explicitly opts for that.

**Comment by overtrue** [comment]
like this?

```php
// SNAPSHOT: $versionable = ['title', 'type']
$post = Post::create(['title' => 'Init title', 'type' => 'Blog', 'status' => 'published'])
$post->update(['title' => 'version 2 title']);
$post->update(['status' => 'draft']); // no version
$post->update(['type' => 'Vlog']);

// versions:
// ['id' => 1, 'title' => 'Init title', 'type' => 'Blog', 'status' => 'published']
// ['id' => 2, 'title' => 'version 2 title', 'type' => 'Blog',]
// ['id' => 3, 'title' => 'version 2 title', 'type' => 'vlog']

$post->revert(2);
// [
//      'title' => 'version 2 title', 
//      'type' => 'Blog', 
//      'status' => 'draft' // latest value, because this field is not in $versionable
// ]

```

**Comment by overtrue** [comment]
OK, if the $versionable is empty, snapshot all?

**Comment by mansoorkhan96** [comment]
> like this?
> 
> ```
> // SNAPSHOT: $versionable = ['title', 'type']
> $post = Post::create(['title' => 'Init title', 'type' => 'Blog', 'status' => 'published'])
> $post->update(['title' => 'version 2 title']);
> $post->update(['status' => 'draft']); // no version
> $post->update(['type' => 'Vlog']);
> 
> // versions:
> // ['id' => 1, 'title' => 'Init title', 'type' => 'Blog', 'status' => 'published']
> // ['id' => 2, 'title' => 'version 2 title', 'type' => 'Blog',]
> // ['id' => 3, 'title' => 'version 2 title', 'type' => 'vlog']
> 
> $post->revert(2);
> // [
> //      'title' => 'version 2 title', 
> //      'type' => 'Blog', 
> //      'status' => 'draft' // latest value, because this field is not in $versionable
> // ]
> ```

Yep, this looks good.

**Comment by mansoorkhan96** [comment]
> OK, if the $versionable is empty, snapshot all?

yes, that should be the default.

**Comment by overtrue** [comment]
> > OK, if the $versionable is empty, snapshot all?
> 
> yes, that should be the default.

Nice! thank you!

**Comment by mansoorkhan96** [comment]
@overtrue FYI, I was inspired by the Wordpress Revisions system. I borrowed some styling from there too.

Maybe you should also try it to see how they handle it. With 0 plugins, when you have updated a post/page 2-3 times. You should see the Revisions button on right side bar and then it opens up the diff page. And it only shows you the diff for the title and content. Its more like what we are doing with snapshot.

https://wordpress.com/support/page-post-revisions/

**Comment by overtrue** [comment]
> @overtrue FYI, I was inspired by the Wordpress Revisions system. I borrowed some styling from there too.
> 
> Maybe you should also try it to see how they handle it. With 0 plugins, when you have updated a post/page 2-3 times. You should see the Revisions button on right side bar and then it opens up the diff page. And it only shows you the diff for the title and content. Its more like what we are doing with snapshot.
> 
> https://wordpress.com/support/page-post-revisions/

OK, thanks.

**Comment by overtrue** [comment]
https://github.com/WordPress/WordPress/blob/master/wp-includes/revision.php#L130

**Comment by mansoorkhan96** [comment]
Also, can we pass an a third option to diff functions like `toSideBySideHtml` to also include attributes that were not changed.

Right now the diff removes the title if it was not changed.

Thanks.

**Comment by overtrue** [comment]
> Also, can we pass an a third option to diff functions like `toSideBySideHtml` to also include attributes that were not changed.
> 
> Right now the diff removes the title if it was not changed.
> 
> Thanks.

Good idea, I will try it after these works.

**Comment by mansoorkhan96** [comment]
> > Also, can we pass an a third option to diff functions like `toSideBySideHtml` to also include attributes that were not changed.
> > Right now the diff removes the title if it was not changed.
> > Thanks.
> 
> Good idea, I will try it after these works.

You are the man.
Thank you so much.

**Comment by overtrue** [comment]
Do you think the initial version should include all attributes?

**Comment by overtrue** [comment]
> Do you think the initial version should include all attributes?

I prefer to Yes.

**Comment by mansoorkhan96** [comment]
> > Do you think the initial version should include all attributes?
> 
> I prefer to Yes.

Well if needed. But then i have to strip them out and only show the $versionable.

**Comment by overtrue** [comment]
> > > Do you think the initial version should include all attributes?
> > 
> > 
> > I prefer to Yes.
> 
> Well if needed. But then i have to strip them out and only show the $versionable.

OK.

**Comment by mansoorkhan96** [comment]
I have hacked your Diff => render method by manually creating a simple diff for identical strings 😈

```php
public function render(string $renderer = null, array $differOptions = [], array $renderOptions = []): array
{
    if (empty($differOptions)) {
        $differOptions = $this->differOptions;
    }

    if (empty($renderOptions)) {
        $renderOptions = $this->renderOptions;
    }

    $fromContents = $this->fromVersion->contents;
    $toContents = $this->toVersion->contents;

    $diff = [];
    $createDiff = function ($key, $old, $new) use (&$diff, $renderer, $differOptions, $renderOptions) {
        if ($renderer) {
            $old = is_string($old) ? $old : json_encode($old);
            $new = is_string($new) ? $new : json_encode($new);

            if ($old === $new) {
                // If there are no changes, write a hardcoded custom diff.
                $diff[$key] = '<table class="diff-wrapper diff diff-html diff-side-by-side"><tbody class="change change-eq"><tr><td class="old">'.$old.'</td><td class="new">'.$new.'</td></tr></tbody></table>';
            } else {
                $diff[$key] = str_replace('\n No newline at end of file', '', DiffHelper::calculate($old, $new, $renderer, $differOptions, $renderOptions));
            }
        } else {
            $diff[$key] = compact('old', 'new');
        }
    };

    // we are not using ArrayDiffMultidimensional, as we dont need to strip out the identical string. so a simple foreach on our attributes
    foreach ($fromContents as $key => $value) {
        $createDiff($key, Arr::get($toContents, $key), Arr::get($fromContents, $key));
    }

    foreach (array_diff_key($fromContents, $toContents) as $key => $value) {
        $createDiff($key, null, $value);
    }

    return $diff;
}
```

**Comment by mansoorkhan96** [comment]
I have opened an issue on PHP Diff package: https://github.com/jfcherng/php-diff/issues/78

**Comment by overtrue** [comment]
> I have hacked your Diff => render method by manually creating a simple diff for identical strings 😈
> 
> ```
> public function render(string $renderer = null, array $differOptions = [], array $renderOptions = []): array
> {
>     if (empty($differOptions)) {
>         $differOptions = $this->differOptions;
>     }
> 
>     if (empty($renderOptions)) {
>         $renderOptions = $this->renderOptions;
>     }
> 
>     $fromContents = $this->fromVersion->contents;
>     $toContents = $this->toVersion->contents;
> 
>     $diff = [];
>     $createDiff = function ($key, $old, $new) use (&$diff, $renderer, $differOptions, $renderOptions) {
>         if ($renderer) {
>             $old = is_string($old) ? $old : json_encode($old);
>             $new = is_string($new) ? $new : json_encode($new);
> 
>             if ($old === $new) {
>                 // If there are no changes, write a hardcoded custom diff.
>                 $diff[$key] = '<table class="diff-wrapper diff diff-html diff-side-by-side"><tbody class="change change-eq"><tr><td class="old">'.$old.'</td><td class="new">'.$new.'</td></tr></tbody></table>';
>             } else {
>                 $diff[$key] = str_replace('\n No newline at end of file', '', DiffHelper::calculate($old, $new, $renderer, $differOptions, $renderOptions));
>             }
>         } else {
>             $diff[$key] = compact('old', 'new');
>         }
>     };
> 
>     // we are not using ArrayDiffMultidimensional, as we dont need to strip out the identical string. so a simple foreach on our attributes
>     foreach ($fromContents as $key => $value) {
>         $createDiff($key, Arr::get($toContents, $key), Arr::get($fromContents, $key));
>     }
> 
>     foreach (array_diff_key($fromContents, $toContents) as $key => $value) {
>         $createDiff($key, null, $value);
>     }
> 
>     return $diff;
> }
> ```

5.x branch seems ready, do you need add this to 5.x ?

**Comment by mansoorkhan96** [comment]
> I have opened an issue on PHP Diff package: [jfcherng/php-diff#78](https://github.com/jfcherng/php-diff/issues/78)

This request was completed by the Diff author 🚀

@overtrue This how your `render` would look now:

```php
public function render(string $renderer = null, array $differOptions = [], array $renderOptions = []): array
{
    if (empty($differOptions)) {
        $differOptions = $this->differOptions;
    }

    if (empty($renderOptions)) {
        $renderOptions = $this->renderOptions;
    }

    $fromContents = $this->fromVersion->contents;
    $toContents = $this->toVersion->contents;

    $diff = [];
    $createDiff = function ($key, $old, $new) use (&$diff, $renderer, $differOptions, $renderOptions) {
        if ($renderer) {
            $old = is_string($old) ? $old : json_encode($old);
            $new = is_string($new) ? $new : json_encode($new);
            $diff[$key] = str_replace('\n No newline at end of file', '', DiffHelper::calculate($old, $new, $renderer, $differOptions, $renderOptions));
        } else {
            $diff[$key] = compact('old', 'new');
        }
    };

    // we are not using ArrayDiffMultidimensional, as we dont need to strip out the identical string. so a simple foreach on our attributes
    foreach ($fromContents as $key => $value) {
        $createDiff($key, Arr::get($toContents, $key), Arr::get($fromContents, $key));
    }

    foreach (array_diff_key($fromContents, $toContents) as $key => $value) {
        $createDiff($key, null, $value);
    }

    return $diff;
}
```

**Comment by overtrue** [comment]
Great!

**Comment by mansoorkhan96** [comment]
> ```
> toContents
> ```

Maybe rename `toContents` and `fromContents` to something `old/new` for readability? thanks.

**Comment by mansoorkhan96** [comment]
Maybe rename `toContents` and `fromContents` to something `old/new` for readability? thanks.

**Comment by overtrue** [comment]
> Maybe rename `toContents` and `fromContents` to something `old/new` for readability? thanks.

ok

**Comment by mansoorkhan96** [comment]
@overtrue Could you please help me understand this line from render method?

I tried to debug and see results and but the loop never runs for me.

```php
foreach (array_diff_key($fromContents, $toContents) as $key => $value) {
    $createDiff($key, null, $value);
}
```

**Comment by mansoorkhan96** [comment]
@overtrue I am using the latest commits from 4.x.

I would have loved to test out the 5.x but unfortunately i have to leave my desk today and I will be only able to test it tomorrow.

**Comment by overtrue** [comment]
> @overtrue I am using the latest commits from 4.x.
> 
> I would have loved to test out the 5.x but unfortunately i have to leave my desk today and I will be only able to test it tomorrow.

No problem.

**Comment by mansoorkhan96** [comment]
> @overtrue I am using the latest commits from 4.x.
> 
> I would have loved to test out the 5.x but unfortunately i have to leave my desk today and I will be only able to test it tomorrow.

I think, we also have to wait for php diff pr merge

**Comment by mansoorkhan96** [comment]
Thank you so much for working on this.
see you tomorrow.

**Comment by overtrue** [comment]
> @overtrue Could you please help me understand this line from render method?
> 
> I tried to debug and see results and but the loop never runs for me.
> 
> ```
> foreach (array_diff_key($fromContents, $toContents) as $key => $value) {
>     $createDiff($key, null, $value);
> }
> ```

`array_diff_key($fromContents, $toContents)` it means `get the keys removed from $fromContents` 

```php
> array_diff_key(['a' => 1, 'b' => 2], ['a' => 2, 'c' => 4])
= [
    "b" => 2,
  ]
```

**Comment by mansoorkhan96** [comment]
@overtrue  I am on 5.x and everything works great.

When you decided to keep all fields to initial version, I thought i have would have to hack around strip out the fields other $versionable. But no man, they are stripped away for me.

Thank you so much for working and improving things.

**Comment by mansoorkhan96** [comment]
https://packagist.org/packages/mansoor/filament-versionable

**Comment by overtrue** [comment]
> @overtrue I am on 5.x and everything works great.
> 
> When you decided to keep all fields to initial version, I thought i have would have to hack around strip out the fields other $versionable. But no man, they are stripped away for me.
> 
> Thank you so much for working and improving things.

I'm still trying to figure out how to design it better, and it seems like everything is designed to be "revert", which may seem a bit inappropriate, but I'm going to think about it over the next few days before releasing a version, and maybe I should update the docs first.

**Comment by overtrue** [comment]
![image](https://github.com/overtrue/laravel-versionable/assets/1472352/2215956f-45f4-4a38-ac4e-ed8f76b917df)
I like the UI design, it's beautiful!

**Comment by overtrue** [comment]
@mansoorkhan96 What do you think about redoing a package for our new version? I don't think versionable is a good word for it because I'm Chinese so I don't know English very well, I think your `Revisions` is a good name, WordPress is named like that too, or the name of the package stays the same but the method names and class names are changed?

**Comment by mansoorkhan96** [comment]
> @mansoorkhan96 What do you think about redoing a package for our new version? I don't think versionable is a good word for it because I'm Chinese so I don't know English very well, I think your `Revisions` is a good name, WordPress is named like that too, or the name of the package stays the same but the method names and class names are changed?

I am also not a native English speaker Lol. But versionable sounds fine, there is another package with the same name by Marcel Pociot. Versionable is not an English word though, you are right about that.

So, how would this work? Would you rename the repository and all the stuff?

**Comment by mansoorkhan96** [comment]
> ![image](https://github.com/overtrue/laravel-versionable/assets/1472352/2215956f-45f4-4a38-ac4e-ed8f76b917df)
> I like the UI design, it's beautiful!

Thanks, that is all Filament. You should try it, if you haven't. Its an amazing package/framework to build stuff like Admin panels.

**Comment by mansoorkhan96** [comment]
@overtrue Possible to tag a minor release of 5.x, so that i can stick to a tested version for some time?
Thanks.

**Comment by overtrue** [comment]
@mansoorkhan96 You can use test version with `"overtrue/laravel-versionable": "dev-5.x" `

**Comment by mansoorkhan96** [comment]
> @mansoorkhan96 You can use test version with `"overtrue/laravel-versionable": "dev-5.x" `

Thats what i am using right now.
But you will be pushing new commits directly to 5.x branch, which might break something. So its better for me to stick to a release. Maybe even 5.x@beta would work?

**Comment by overtrue** [comment]
@mansoorkhan96 I got it, now it's here https://github.com/overtrue/laravel-versionable/releases/tag/5.0.0-beta.1

**Comment by overtrue** [comment]
@mansoorkhan96 

I would like to remove the "initialized version contains all attributes" design, I think since `$versionable` specifies which fields need version control, the rollback should only affect `$versionable` fields, not "all attributes of the model at the time of the specified version", I think it should not be configured if all fields need to be controlled. If all fields need to be controlled, then `$versionable` should be left unconfigured. Do you agree with this idea?

**Comment by mansoorkhan96** [comment]
> @mansoorkhan96 
> 
> I would like to remove the "initialized version contains all attributes" design, I think since `$versionable` specifies which fields need version control, the rollback should only affect `$versionable` fields, not "all attributes of the model at the time of the specified version", I think it should not be configured if all fields need to be controlled. If all fields need to be controlled, then `$versionable` should be left unconfigured. Do you agree with this idea?

I agree, actually that's what i was suggesting in our earlier discussion. I thought you needed all attributes for revert mechanism.
Keeping only the $versionable fields sounds good to me

**Comment by overtrue** [comment]
> > @mansoorkhan96
> > I would like to remove the "initialized version contains all attributes" design, I think since `$versionable` specifies which fields need version control, the rollback should only affect `$versionable` fields, not "all attributes of the model at the time of the specified version", I think it should not be configured if all fields need to be controlled. If all fields need to be controlled, then `$versionable` should be left unconfigured. Do you agree with this idea?
> 
> I agree, actually that's what i was suggesting in our earlier discussion. I thought you needed all attributes for revert mechanism. Keeping only the $versionable fields sounds good to me

I did it.

**Comment by overtrue** [comment]
@mansoorkhan96 https://github.com/overtrue/laravel-versionable/releases/tag/5.0.0
