### ISSUE TITLE
Problem with getVersionUserId()

### ISSUE THREAD

**Issue by Arthur-Zaripov** [overtrue/laravel-versionable#87]
Hello! 
Package version 4. 

    public function getVersionUserId()
    {
        return auth()->id() ?? $this->getAttribute(\config('versionable.user_foreign_key'));
    }

 Package version 5. 

```
   public function getVersionUserId()
    {
        return $this->getAttribute($this->getUserForeignKeyName()) ?? auth()->id();
    }
```
    
Is method correct in version 5? 
Method $this->getAttribute() throws MissingAttributeException if Model::shouldBeStrict() is enabled in model.
https://laravel-news.com/shouldbestrict
So method  getVersionUserId() from package version 5 could return error.

**Comment by overtrue** [comment]
so your versionable model doesn't have the `user_id` attribute？

**Comment by zorca** [comment]
Faced with this situation. My model does not contain a user_id, but I add it at the stage of creating the version using the model observer.
May be create config option for disable auto-create version user? Or make method getVersionUserId safe for nullable user models?
